- client/src/assets/styles/variables.scss
- client/src/common/translation/i18n/en.json
- client/src/common/translation/i18n/fi.json
- client/src/common/translation/i18n/sv.json
- client/src/domain/event/EventPageContainer.tsx
- client/src/domain/event/SimilarEventCard.tsx
- client/src/domain/event/SimilarEvents.tsx
- client/src/domain/event/constants.ts
- client/src/domain/event/similarEventCard.module.scss
- client/src/domain/event/similarEvents.module.scss
- client/src/domain/eventSearch/EventSearchPageContainer.tsx
https://helsinkisolutionoffice.atlassian.net/browse/TH-154
> TH-154 | Display similar events on event page

- client/src/common/translation/i18n/en.json
- client/src/common/translation/i18n/fi.json
- client/src/common/translation/i18n/sv.json
- client/src/domain/event/EventClosedHero.tsx
- client/src/domain/event/EventPageContainer.tsx
- client/src/domain/event/EventUtils.ts
- client/src/domain/event/eventClosedHero.module.scss
- client/src/domain/event/similarEvents.module.scss
https://helsinkisolutionoffice.atlassian.net/browse/TH-164
> TH-164 | Display info text if event is already ended

- client/src/common/components/dateSelector/__tests__/__snapshots__/DataRangeInputs.test.tsx.snap
- client/src/common/components/dateSelector/dateSelectorMenu.module.scss
- client/src/common/components/filterButton/FilterButton.tsx
- client/src/common/components/filterButton/filterButton.module.scss
- client/src/common/translation/i18n/en.json
- client/src/common/translation/i18n/fi.json
- client/src/common/translation/i18n/sv.json
- client/src/domain/app/footer/topFooter.module.scss
- client/src/domain/app/mobileNavigation/mobileNavigationMenu/mobileNavigationMenu.module.scss
- client/src/domain/eventSearch/DateFilter.tsx
- client/src/domain/eventSearch/EventListUtils.ts
- client/src/domain/eventSearch/EventSearchPageContainer.tsx
- client/src/domain/eventSearch/Search.tsx
- client/src/domain/eventSearch/SearchResultList.tsx
- client/src/domain/eventSearch/query.ts
- client/src/domain/eventSearch/search.module.scss
- client/src/domain/eventSearch/searchResultList.module.scss
- client/src/generated/graphql.tsx
- client/src/util/__tests__/getUrlParamAsString.ts
- client/src/util/getUrlParamAsString.ts
- graphql-proxy/src/schema/event/resolvers.ts
- graphql-proxy/src/schema/event/typeDefs.ts
https://helsinkisolutionoffice.atlassian.net/browse/TH-172
> TH-172 | Filter by date range

- README.md
> TH-183 | Add instructions for debugging social media sharing

- gitlab-ci.yml
https://helsinkisolutionoffice.atlassian.net/browse/TH-156
> TH-156 | Add gitlab ci settings

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/eventSearch/SearchResultList.tsx
- src/domain/eventSearch/searchResultList.module.scss
https://helsinkisolutionoffice.atlassian.net/browse/TH-219
> TH-219 | Button to clear event search filters

- src/domain/collection/CollectionPageContainer.tsx
- src/domain/collection/eventList/EventList.tsx
- src/domain/collection/query.ts
- src/domain/eventSearch/EventListUtils.ts
- src/domain/eventSearch/FilterSummary.tsx
- src/domain/eventSearch/SearchResultList.tsx
- src/domain/eventSearch/filterSummary.module.scss
- src/domain/eventSearch/searchResultList.module.scss
- src/generated/graphql.tsx
https://helsinkisolutionoffice.atlassian.net/browse/TH-205
> TH-205 | Event list on collection page

- src/domain/collection/eventList/EventList.tsx
- src/domain/collection/eventList/__tests__/EventList.test.tsx
- src/domain/event/SimilarEvents.tsx
- src/domain/eventSearch/EventListUtils.ts
- src/domain/eventSearch/EventSearchPageContainer.tsx
- src/domain/eventSearch/query.ts
- src/generated/graphql.tsx
https://helsinkisolutionoffice.atlassian.net/browse/TH-245
> TH-245 | Filter event list by language

- src/common/components/keyword/Keyword.tsx
- src/common/components/keyword/keyword.module.scss
- src/domain/event/EventKeywords.tsx
- src/domain/eventSearch/EventCard.tsx
https://helsinkisolutionoffice.atlassian.net/browse/TH-242
> TH-242 | Hide keywords on mobile on event list cards

- src/domain/eventSearch/EventListUtils.ts
https://helsinkisolutionoffice.atlassian.net/browse/TH-259
> TH-259 | Always set current time to start time if selected start time is in past

- src/common/components/multiSelectDropdown/DropdownMenu.tsx
- src/common/components/multiSelectDropdown/MultiSelectDropdown.tsx
- src/common/components/multiSelectDropdown/dropdownMenu.module.scss
- src/common/components/search/SearchAutosuggest.tsx
- src/common/components/search/autosuggestMenu.module.scss
- src/domain/eventSearch/Search.tsx
- src/domain/eventSearch/search.module.scss
- src/domain/eventSearch/searchResultList/searchResultList.module.scss
- src/domain/home/Search.tsx
https://helsinkisolutionoffice.atlassian.net/browse/TH-332
> TH-332 | Submit search form by pressing enter

- config/paths.js
- config/webpack.server.config.js
Modify webpack server config file to match same version as create react app
Run command `yarn build` and after build `yarn start:server`
> Webpack configuration

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/eventSearch/Search.tsx
- src/domain/eventSearch/constants.ts
- src/domain/eventSearch/query.ts
- src/domain/eventSearch/types.ts
- src/domain/eventSearch/utils.ts
- src/generated/graphql.tsx
Add checkbox to filter evening events
TH-648
> TH-648 | Add checkbox to show only evening events

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/app/__tests__/BrowserApp.test.tsx
- src/domain/collection/CollectionPageContainer.tsx
- src/domain/collection/CollectionUtils.ts
- src/domain/collection/__mocks__/collection.ts
- src/domain/collection/__tests__/CollectionPageContainer.test.tsx
- src/domain/collection/query.ts
- src/domain/collectionList/CollectionListPage.tsx
- src/domain/collectionList/__tests__/CollectionListPage.test.tsx
- src/domain/landingPage/LandingPage.tsx
- src/generated/graphql.tsx
Show error hero if collection is expired
Hide expired collections from collection lists
TH-517
> TH-517 | Expired collections error page

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/about/AboutPage.tsx
- src/domain/about/AboutPageEn.tsx
- src/domain/about/AboutPageFi.tsx
- src/domain/about/AboutPageSv.tsx
- src/domain/about/__tests__/AboutPage.test.tsx
- src/domain/about/__tests__/AboutPageEn.test.tsx
- src/domain/about/__tests__/AboutPageFi.test.tsx
- src/domain/about/__tests__/AboutPageSv.test.tsx
- src/domain/about/__tests__/__snapshots__/AboutPageEn.test.tsx.snap
- src/domain/about/__tests__/__snapshots__/AboutPageFi.test.tsx.snap
- src/domain/about/__tests__/__snapshots__/AboutPageSv.test.tsx.snap
- src/domain/about/aboutPage.module.scss
- src/domain/about/hero/Hero.tsx
- src/domain/about/hero/hero.module.scss
- src/domain/app/App.tsx
Implements about page
**[TH-752](https://helsinkisolutionoffice.atlassian.net/browse/TH-752)**
> About page

- src/common/translation/i18n/en.json
- src/common/translation/i18n/sv.json
Update English and Swedish translations
[TH-737](https://helsinkisolutionoffice.atlassian.net/browse/TH-737)
> TH-737 | Update English and Swedish translations

- src/common/components/collectionCard/CollectionCardContainer.tsx
- src/common/components/collectionCard/__tests__/__snapshots__/CollectionCards.test.tsx.snap
- src/domain/collection/CollectionUtils.ts
- src/domain/collection/__tests__/__snapshots__/CollectionPageContainer.test.tsx.snap
- src/domain/collection/collectionHero/CollectionHero.tsx
- src/domain/collection/collectionHero/__tests__/__snapshots__/CollectionHero.test.tsx.snap
- src/domain/collection/collectionHero/collectionHero.module.scss
- src/domain/collection/collectionPageMeta/CollectionPageMeta.tsx
- src/domain/collection/similarCollections/SimilarCollections.tsx
Update collection hero layout
Hide collection description if there is no translation on selected language
Filter expired collections out from similar collections
**[TH-777](https://helsinkisolutionoffice.atlassian.net/browse/TH-777)**
**[TH-784](https://helsinkisolutionoffice.atlassian.net/browse/TH-784)**
> TH-777, TH-784 | Improvement/collection hero layout

- src/domain/event/eventHero/EventHero.tsx
- src/domain/event/eventHero/eventHero.module.scss
**[TH-788](https://helsinkisolutionoffice.atlassian.net/browse/TH-788)**
> TH-788 | Set event page content more readable order and re-order content on css

- src/common/components/languageDropdown/LanguageDropdown.tsx
- src/common/components/languageDropdown/languageDropdown.module.scss
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
Pronounce language option in target language
Improve translations
**[TH-787](https://helsinkisolutionoffice.atlassian.net/browse/TH-787)**
> TH-787 | Language selector accessibility improvements

- .eslintrc.json
- .testcaferc.json
- README.md
- package.json
- testcafe/e2e/changeLanguage.ts
- testcafe/selectors/header.ts
- testcafe/utils/clientUtils.ts
- testcafe/utils/settings.ts
- tsconfig.testcafe.json
- yarn.lock
TestCafe setup
Test change language feature
> TestCafe setup

- src/common/components/eventCard/EventCard.tsx
- src/common/components/eventCard/LargeEventCard.tsx
- src/common/components/eventCard/__tests__/EventCard.test.tsx
- src/common/components/eventCard/__tests__/LargeEventCard.test.tsx
- src/domain/event/EventUtils.ts
- src/domain/event/eventContent/EventContent.tsx
- src/domain/event/eventHero/EventHero.tsx
- src/domain/event/eventInfo/EventInfo.tsx
- src/domain/event/eventInfo/__tests__/__snapshots__/EventInfo.test.tsx.snap
- src/domain/event/eventLocation/EventLocation.tsx
- src/domain/event/eventName/EventName.tsx
- src/domain/event/eventPageMeta/EventPageMeta.tsx
- src/domain/event/eventPageMeta/__tests__/EventPageMeta.test.tsx
- src/domain/landingPage/landingPageHero/__tests__/__snapshots__/LandingPageHero.test.tsx.snap
Add helper function to get event fields
Use that helper function to unify way to get fields for components
> Helper function to get event fields

- src/domain/app/routes/__tests__/AppRoutes.test.tsx
- src/domain/event/eventCard/EventCard.tsx
- src/domain/event/eventCard/LargeEventCard.tsx
- src/domain/event/eventCard/__tests__/EventCard.test.tsx
- src/domain/event/eventCard/__tests__/LargeEventCard.test.tsx
- src/domain/event/eventCard/utils.ts
- src/domain/eventSearch/constants.ts
- Add malmitalo and fix back button functionality on event page
**[TH-902](https://helsinkisolutionoffice.atlassian.net/browse/TH-902):**
> Add malmitalo and fix back button functionaliy on event page

- public/robots.txt
- src/domain/collectionList/CollectionListPage.tsx
- src/domain/eventSearch/EventSearchPageContainer.tsx
- src/util/updateSitemap.ts
- Add metadata to collections page
- Add metadata to events search page
- Add missing paths to sitemaps generator
**[TH-903](https://helsinkisolutionoffice.atlassian.net/browse/TH-903):** 
**[TH-905](https://helsinkisolutionoffice.atlassian.net/browse/TH-905):**
> TH-903, TH-905 | Add missing path from sitemap generator + add meta data

- .huskyrc
- .lintstagedrc
- .prettierrc.json
- package.json
- src/common/components/dateRangePicker/__tests/DateRangePicker.test.tsx
- src/common/components/link/__tests__/IconLink.test.tsx
- src/common/components/scrollIntoViewWithFocus/__tests__/ScrollIntoViewWithFocus.test.tsx
- src/domain/app/routes/__tests__/AppRoutes.test.tsx
- src/domain/collection/similarCollections/__tests__/SimilarCollections.test.tsx
- src/domain/event/EventUtils.ts
- src/domain/event/eventInfo/__tests__/OtherEventTimes.test.tsx
- src/domain/eventSearch/__tests__/EventSearchPageContainer.test.tsx
- src/domain/eventSearch/__tests__/Search.test.tsx
- src/domain/eventSearch/__tests__/utils.test.ts
- src/domain/eventSearch/utils.tsx
- src/domain/landingPage/landingPageSearch/__tests__/LandingPageSearch.test.tsx
- src/domain/landingPage/utils.ts
- src/hooks/useResetState.tsx
- src/util/date-fns/locale/buildLocalizeFn.ts
- src/util/updateSitemap.ts
- yarn.lock
-Uses linter and prettier before committing changes.
-Runs tests automatically before pushing the changes.
-Fixes the existing lint errors and warnings.
> Add husky and lint-staged configuration

- src/domain/app/routes/__tests__/AppRoutes.test.tsx
> Fix tests in Approutes

- src/domain/landingPage/landingPageHero/__tests__/LandingPageHero.test.tsx
- src/hooks/__tests__/useTextWrapperWidth.test.tsx
-fixed unit tests for windows.
-removed redundant unit tests.
> TH-937: Fix unit tests for windows

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/courseSearch/Search.tsx
- src/domain/courseSearch/__tests__/Search.test.tsx
> TH-899: Add isFree checkbox and search logic to courses search

- .lintstagedrc.js
> Fix lint-staged format-code

- src/server/Html.tsx
- src/server/__tests__/__snapshots__/Html.test.tsx.snap
> TH-926: Fixes initial lang attribute

- src/generated/graphql.tsx
> update graphql types (Remove unused landingpage fields)

- src/common/components/rangeDropdown/RangeDropdown.tsx
- src/common/components/rangeDropdown/__tests__/RangeDropdown.test.tsx
- src/domain/courseSearch/Search.tsx
- src/domain/courseSearch/__tests__/Search.test.tsx
- src/domain/eventSearch/constants.ts
- Fix delete filter bug
- Improve tests
- small refactor
> TH-898 | Improve tests + small refactor

- .github/workflows/production.yml
> Add dependency and an extra variable to prod workflow

- src/common/components/rangeDropdown/RangeDropdown.tsx
- src/common/components/rangeDropdown/__tests__/RangeDropdown.test.tsx
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/courseSearch/Search.tsx
- src/domain/courseSearch/__tests__/Search.test.tsx
- src/domain/eventSearch/filterSummary/__tests__/AgeFilter.test.tsx
- src/domain/eventSearch/filterSummary/__tests__/__snapshots__/AgeFilter.test.tsx.snap
> TH-984: Improves courses search target group dropdown

- src/common/components/rangeDropdown/rangeDropdown.module.scss
> Fixes clear all outline in range dropdown

- src/domain/courseSearch/Search.tsx
- src/domain/courseSearch/__tests__/CourseSearchPageContainer.test.tsx
> TH-1040: Temporally hide area search from courses

- src/domain/event/eventCard/__tests__/LargeEventCard.test.tsx
- src/domain/event/similarEvents/__tests__/SimilarEvents.test.tsx
> Fix tests action errors

- .github/workflows/load_tests.yml
- README.md
- k6LoadTests.js
> TH-1026, 1031, 1033: K6 load tests

- src/common/components/rangeDropdown/RangeDropdown.tsx
> TH-1049: Improves handling of negative values in age filter

- .github/workflows/review.yml
> Multiple deployments

- browser-tests/datasources/searchFilterDataSource.ts
- src/hooks/useDivisionOptions.tsx
> Include blocklist in neighborhoodtest

- browser-tests/utils/generated/graphql.ts
- src/domain/event/EventUtils.ts
- src/domain/event/eventCard/LargeEventCard.tsx
- src/domain/event/eventCard/largeEventCard.module.scss
- src/domain/event/eventInfo/EventInfo.tsx
- src/domain/event/query.ts
- src/generated/graphql.tsx
> TH-1076: Show target age in event cards

- src/domain/eventSearch/__tests__/EventSearchPageContainer.test.tsx
- src/domain/place/placeSelector/PlaceSelector.tsx
- src/domain/place/placeSelector/__tests__/PlaceSelector.test.tsx
- Fix apollo client loading bug (cache)
> Fix apollo client loading bug (cache)

- browser-tests/datasources/eventDataSource.ts
- src/domain/eventSearch/searchResultList/__tests__/ResultsInfo.test.tsx
> Added test for  language change button on search results.

- src/domain/event/eventInfo/EventInfo.tsx
- src/domain/event/eventInfo/__tests__/EventInfo.test.tsx
TH-1115.
NOTE: I think it would be good to resolve and merge LinkedEvents V2 changes before this PR is merged.
> Hide the amount of max attendees and remaining spots from other info section.

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/event/eventInfo/OrganizationInfo.tsx
- src/domain/event/eventInfo/__tests__/EventInfo.test.tsx
TH-999. Cherry picked the one and only commit from the old pull request #211 made for same ticket . It was so much behind that it was easier to start from scratch.
> Own details sections for publisher and provider.

- src/domain/eventSearch/searchResultList/ResultsInfo.tsx
- src/domain/eventSearch/searchResultList/__tests__/ResultsInfo.test.tsx
- src/domain/eventSearch/searchResultList/__tests__/SearchResultsContainer.test.tsx
> Add feature flag check to results info (do not show small text)

- browser-tests/utils/generated/graphql.ts
- src/domain/event/__tests__/CoursePageContainer.test.tsx
- src/domain/eventSearch/query.ts
- src/generated/graphql.tsx
> TH-1145 | Fix age filter bug

- src/common/translation/i18n/sv.json
- Fix couple swedish translations
**[TH-1124](https://helsinkisolutionoffice.atlassian.net/browse/TH-1124):** 
**[TH-1122](https://helsinkisolutionoffice.atlassian.net/browse/TH-1122):**
> SV translation fixes

- src/domain/eventSearch/SearchPage.tsx
- src/domain/eventSearch/eventSearchPage.module.scss
> Fix z-index problem with notification in result list

- browser-tests/utils/generated/graphql.ts
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/eventSearch/Search.tsx
- src/domain/eventSearch/SearchPage.tsx
- src/domain/eventSearch/__tests__/EventSearchPageContainer.test.tsx
- src/domain/eventSearch/__tests__/Search.test.tsx
- src/domain/eventSearch/constants.ts
- src/domain/eventSearch/query.ts
- src/domain/eventSearch/types.ts
- src/domain/eventSearch/utils.tsx
- src/generated/graphql.tsx
- Add remote events checkbox to events search
**[TH-1061](https://helsinkisolutionoffice.atlassian.net/browse/TH-1061):**
> TH-1061 | Add remote events checkbox to events search

- src/domain/courseSearch/__tests__/CourseSearchPageContainer.test.tsx
- src/domain/eventSearch/__tests__/Search.test.tsx
- src/domain/eventSearch/filterSummary/FilterSummary.tsx
- src/domain/neighborhood/additionalDivisions.ts
- src/hooks/useDivisionOptions.tsx
- Add additional division to division dropdown
**[TH-921](https://helsinkisolutionoffice.atlassian.net/browse/TH-921):**
> TH-921 | Add additional divisions

- src/constants.ts
- src/domain/courseSearch/Search.tsx
- Localize feedback link for info ribbon
> TH-1109 | Localized feedback link

- src/domain/app/footer/footer.module.scss
- tsconfig.json
> Fix wave background issue with more negative margin

- browser-tests/utils/generated/graphql.ts
- src/domain/collection/__tests__/CollectionPageContainer.test.tsx
- src/domain/collection/curatedEvents/__tests__/CuratedEvents.test.tsx
- src/domain/collection/curatedEvents/usePaginatedEventsByIdsQuery.tsx
- src/domain/eventSearch/query.ts
- src/generated/graphql.tsx
TH-1165. Needs changes from proxy which are implemented in this pull request https://github.com/City-of-Helsinki/events-helsinki-api-proxy/pull/75.
Added eventTypes to variables:
> Added eventType to eventsByIds query.

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
> Added open in a new tab -aria-labels to share links.

- src/common/components/filterButton/FilterButton.tsx
- src/common/components/filterButton/types.ts
- src/domain/eventSearch/filterSummary/AgeFilter.tsx
- src/domain/eventSearch/filterSummary/DateFilter.tsx
- src/domain/eventSearch/filterSummary/FilterSummary.tsx
- src/domain/eventSearch/filterSummary/PlaceFilter.tsx
- src/domain/eventSearch/filterSummary/PublisherFilter.tsx
- src/domain/eventSearch/filterSummary/TextFilter.tsx
- src/domain/eventSearch/utils.tsx
TH-1103. There was a circular import, which wrecked the css import. Also the parameter type was wrong in normalizeSuitableFor - it was a list of string or numbers, but it should be a list of mixed items..
> Fixed TS compilation error on browser tests.

- src/common/translation/i18n/sv.json
- src/util/__tests__/dateUtils.test.tsx
- src/util/dateUtils.ts
> TH-954 | Add missing translation for datepicker and update date formatting

- src/common/components/dateRangePicker/DateRangePicker.tsx
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**
> disable autocomplete from datepickers to make screen reader work better

- .husky/commit-msg
- CHANGELOG.md
- README.md
- commitlint.config.js
- package.json
- yarn.lock
**[TH-939](https://helsinkisolutionoffice.atlassian.net/browse/TH-939):**
> TH-939 | Standard version

- browser-tests/utils/generated/graphql.ts
- src/domain/collection/__tests__/CollectionPageContainer.test.tsx
- src/domain/collection/curatedEvents/__tests__/CuratedEvents.test.tsx
- src/domain/collection/curatedEvents/usePaginatedEventsByIdsQuery.tsx
- src/domain/eventSearch/query.ts
- src/generated/graphql.tsx
TH-1183. Added a start parameter to events by ids query.
NOTE: Needs changes from proxy https://github.com/City-of-Helsinki/events-helsinki-api-proxy/pull/82
> fix: show only the upcoming events in a list of curated events

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/event/eventInfo/EventInfo.tsx
- src/domain/event/eventInfo/__tests__/EventInfo.test.tsx
> feat: show the age limits in the event details
