City-of-Helsinki/events-helsinki-ui

src/server/Html.tsx
src/server/__tests__/Html.test.tsx
src/server/__tests__/__snapshots__/Html.test.tsx.snap
src/server/index.ts
src/util/getDomainFromRequest.ts

In order to provide a proper url property for open graph, i.e.
Facebook, we must use the original request as the source. This makes
it easy to apply this meta information on the server side.
In order to complete TH-178, we only need this meta information on the
events page, but with this commit we are applying it to all responses.
I've also applied more generic canonical url link, which is used by
search engines.
--------
https://helsinkisolutionoffice.atlassian.net/secure/RapidBoard.jspa?rapidView=21&modal=detail&selectedIssue=TH-188
I had some trouble getting a good vision of how the canonical url should be managed. As far as I understand, with a SSR setup, we have to use the request express provides to get a complete url. This makes it rather straight forward to apply this meta …

TH-188 | Add a canonical url into the page meta

---

README.md
package.json
public/index.html
src/domain/event/EventPageContainer.tsx
src/domain/event/EventPageMeta.tsx
src/domain/event/__tests__/EventPageMeta.test.jsx
src/setupTests.ts
yarn.lock

Facebook, Twitter and LinkedIn have been taken into account. Adds a
section into readme that covers requirements for metadata.
I also added a new dependecy in @testing-library/react. At the time of
this commit, it was recommended  by create-react-application.
ref: TH-184

TH-184 | Add meta information for social media sharing

---

README.md
package.json
public/index.html
src/domain/event/EventPageContainer.tsx
src/domain/event/EventPageMeta.tsx
src/domain/event/__tests__/EventPageMeta.test.jsx
src/setupTests.ts
yarn.lock

Facebook, Twitter and LinkedIn have been taken into account. Adds a
section into readme that covers requirements for metadata.
I also added a new dependecy in @testing-library/react. At the time of
this commit, it was recommended  by create-react-application.
ref: TH-184

Add meta information for social media sharing

---

src/common/components/search/AutosuggestMenu.tsx

In this 3b6cb637f81d6e4f187d17cb1cfd9cef18b0298f commit, I used the old type for applying the location icon.

Fix missing location icon

---

src/domain/event/EventPageMeta.tsx
src/domain/event/__tests__/EventPageMeta.test.jsx

ShortDescription is more suitable as it is shorter and does not contain
markup that should be parsed.

Use shortDescription for page metadata

---

src/common/components/dateSelector/DateRangeInputs.tsx
src/common/components/dateSelector/DateRangePicker.tsx
src/common/components/dateSelector/DateSelectorMenu.tsx
src/common/components/dateSelector/__tests__/__snapshots__/DateSelectorMenu.test.tsx.snap
src/common/components/dateSelector/datePicker.scss
src/domain/event/SimilarEvents.tsx
src/domain/eventSearch/EventListUtils.ts
src/domain/eventSearch/EventSearchPageContainer.tsx
src/domain/eventSearch/constants.ts
src/domain/eventSearch/query.ts
src/generated/graphql.tsx

Hide past events from the event search results. Also disable past dates from the datepicker. I also removed all option from date range filter menu
https://helsinkisolutionoffice.atlassian.net/browse/TH-214
Also display search results in chronological order
https://helsinkisolutionoffice.atlassian.net/browse/TH-218

TH-214 | Hide past event 

---

src/common/components/dateSelector/dateSelector.module.scss
src/common/components/multiSelectDropdown/multiSelectDropdown.module.scss

We are listening for click events on the document to know when the user
clicks outside of the dropdown. We use this information to close the
dropdown.
We are repalcing the icon-angle-down with icon-angle-up when we
open the menu.
This results in a conflicting scenario. When this element ends up being
the click target, we will fail to find it from within the dropdown
element, because it gets replaced. This leads us to believe that the
element must then be outside of the dropdown, when in truth it does no
longer exist at all. Due to this, we end up closing the menu right after
we opened it, making it look like the menu does not open at all.
To stop this from happening, we are disabling pointer events for the
icons. That way the click will target their parent element, which is
not …

TH-221 | Fix angle icon not opening dropdown

---

src/domain/eventSearch/EventListUtils.ts
src/domain/eventSearch/constants.ts

These were defined by the project manager. Further documentation can be
found from TH-226.
-----
I created a new keyword dictionary. I used the official terminology I could find which is why some keys are in Finnish and some are English. If you know a better method, I am listening :D I translated the Finnish keywords in the comments in order to avoid the situation where someone is lead to think that dev translations are official.
I wanted to use a dictionary in order to provide a human legible label for developers. This should make it easier when new ones are added or old ones are removed.
I added all the keywords in the Jira issue. There were lots of other tags which looked like they could be relevant as well, but I avoided them for now.
The only exception is `Teatteri`. The list …

TH-226 | Include additional keywords for category culture search

---

src/constants.ts
src/domain/landingPage/landingPageHero/LandingPageHero.tsx
src/domain/landingPage/landingPageHero/__tests__/__snapshots__/LandingPageHero.test.tsx.snap
src/domain/landingPage/landingPageHero/landingPageHero.module.scss
src/hooks/__tests__/useBreakpoint.test.tsx
src/hooks/__tests__/useTextWrapperWidth.test.tsx
src/hooks/useBreakpoint.tsx
src/hooks/useTextWrapperWidth.tsx
src/types.ts

Calculate max-width of landing page text container to have event padding
**[TH-795](https://helsinkisolutionoffice.atlassian.net/browse/TH-795)**

TH-795 | Landing page hero improvements

---

package.json
public/index.html
src/domain/landingPage/landingPageHero/landingPageHero.module.scss
src/domain/landingPage/landingPageSearch/landingPageSearch.module.scss
src/index.tsx

Fix `TextEncoder not defined` for Microsoft Edge 44.18362.449.0
Fix small layout problems for Microsoft Edge 44.18362.449.0
[TH-879](https://helsinkisolutionoffice.atlassian.net/browse/TH-879)
Can be tested e.g. using Browser stack: https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=18.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fevents-helsinki-ui-qa-r-fix-edge-pol-zv2jqv.test.kuva.hel.ninja&speed=1

TH-879 | Add polyfills for Edge

---

.env
src/domain/app/routes/__tests__/AppRoutes.test.tsx
src/domain/collection/eventList/__tests__/EventList.test.tsx
src/domain/event/similarEvents/__tests__/SimilarEvents.test.tsx
src/domain/eventSearch/__tests__/EventSearchPageContainer.test.tsx
src/domain/eventSearch/query.ts
src/domain/eventSearch/utils.tsx
src/generated/graphql.tsx

Replace usage of `combinedText` with `allOngoingAnd`. This will have better performance (TH-918) and also includes online events (TH925).
related events-helsinki-api-proxy pr: https://github.com/City-of-Helsinki/events-helsinki-api-proxy/pull/33
https://helsinkisolutionoffice.atlassian.net/browse/TH-918
https://helsinkisolutionoffice.atlassian.net/browse/TH-925 (basically duplicate)

TH-918: use allOngoingAnd instead of combinedText

---

src/domain/app/routes/__tests__/AppRoutes.test.tsx
src/domain/event/similarEvents/__tests__/SimilarEvents.test.tsx
src/domain/eventSearch/query.ts
src/domain/eventSearch/utils.tsx
src/generated/graphql.tsx

Fix problem that division is ignored from event search. Also use always localOngoingSearch when division is selected in order to remove onlineEvents from division searches.
Tried to write regression test but it went too complicated because of complex apollo mocks that wont fit on this scenario.

Fix division in event search

---

src/domain/eventSearch/__tests__/utils.test.ts

TH-918: Added unit tests for onGoing-event list parameters. Also added some division parameter tests
https://helsinkisolutionoffice.atlassian.net/browse/TH-918

TH-918: Added unit tests for onGoing-event list parameters

---

.dockerignore
Dockerfile
README.md
docker-compose.yml
package.prod.json

- Update Dockerfile to generate smaller image
Production build seems to have one external dependency (canvas). We can reduce the final image size by just installing that package in the image. Seems to work.
There seemed to be some errors if you try to remove the external dependecy from webpack config.

TH-938 | Update Dockerfile to generate smaller image

---

.huskyrc
.lintstagedrc
.lintstagedrc.js

If you have regenerated `graphql.tsx` which is ignored, you get the following failure on pre-commit becayse the file is picked up by changed files:
`0:0 warning File ignored because of a matching ignore pattern. Use “--no-ignore” to override`
This will fix the problem.

Fix: Lint stage skips ignored files

---

.github/workflows/staging.yml

As the title says, let's start to deploy to staging from master instead of develop. Develop is still left for the gitlab.

Deploy to staging from master branch

---

src/domain/landingPage/utils.ts
src/generated/graphql.tsx

Fix this one on master (coming after codegen for latest api-proxy):
```
TypeScript error in /Users/codelicious/workspace/events-helsinki-ui/src/domain/landingPage/utils.ts(15,30):
Property 'title' does not exist on type 'LandingPageFieldsFragment'.  TS2339
13 |   locale: Language
14 | ): boolean => {
> 15 |   return Boolean(landingPage.title?.[locale]);
|                              ^
16 | };
```

Fix broken code after codegen

---

src/util/getDomainFromRequest.ts

Fix canonical URL to have https as protovol
**[TH-928](https://helsinkisolutionoffice.atlassian.net/browse/TH-928):**

TH-928 | Fix canonical URL http -> https

---

.gitignore
testcafe/e2e/changeLanguage.ts
testcafe/utils/jsErrorHandler.ts

Fix resize observer problem in testcafe: https://github.com/DevExpress/testcafe/issues/4857#issuecomment-598775956
Originally failed build is here: https://github.com/City-of-Helsinki/events-helsinki-ui/pull/180/checks?check_run_id=1701632369

Fix resize observer problem

---

src/domain/app/routes/LocaleRoutes.tsx
src/domain/app/routes/__tests__/AppRoutes.test.tsx
src/domain/app/routes/constants.ts
src/domain/collection/__tests__/CollectionPageContainer.test.tsx
src/domain/collection/collectionCard/__tests__/CollectionCard.test.tsx
src/domain/eventSearch/__tests__/contants.test.ts
src/domain/eventSearch/constants.ts

Marketing url functionality + talviloma added as fixed marketing slug
https://helsinkisolutionoffice.atlassian.net/browse/TH-980

Th-980: Marketing urls: talviloma

---

browser-tests/utils/url.utils.ts

Avoid errors like this: https://github.com/City-of-Helsinki/events-helsinki-ui/runs/1862824623?check_suite_focus=true
```
------------------------------------------------
: expected '/fi/collection/tapahtumat-kev%C3%A4t' to deeply equal
'/fi/collection/tapahtumat-kevät'
+ expected - actual
-'/fi/collection/tapahtumat-kev%C3%A4t'
+'/fi/collection/tapahtumat-kevät'
Browser: Chrome 88.0.4324.104 / Windows 10
Screenshot:
```

fix encoding in url paths in browser tests

---

browser-tests/common.components.ts
browser-tests/event-search/eventSearchPage.testcafe.ts
browser-tests/utils/regexp.util.ts
browser-tests/utils/url.utils.ts

Browser tests fails occasionally for two reasons:
- 1:  https://helsinkisolutionoffice.atlassian.net/browse/TH-1014 : Event cannot be found by searching tag name with brackets. This can be fixed from our side by stripping out brackets and search by either the part outside the brackets or inside the brackets: For example if keyword is: `Play (Children games)`, let's search either by `Play` or `Children games`. This failure has happened also on event title search, so let's use this random sentence pick in every free text search.
- 2: Sometimes page title says that collection is still loading, example failure: https://github.com/City-of-Helsinki/events-helsinki-ui/pull/180/checks?check_run_id=1910892461
```
: expected 'Ladataan tapahtumaa... - Tapahtumat' to deeply equal
'Maahanmuuttajien …
```

TH-1014: Stabilize browser tests

---

src/domain/event/eventHero/EventHero.tsx
src/domain/event/eventHero/__tests__/EventHero.test.tsx
src/domain/event/eventHero/eventHero.module.scss

Adds local event (type course) time to the hero under the location, when main event date is defined.

TH-1006: Add local event time to event hero

---

src/domain/banner/bannerHero/BannerHero.tsx
src/domain/banner/bannerUtils.ts

TH-1069. TestCafe imported source code in wrong order. Moved BannerHero props to utils. Utils should not import jsx-component.

Moved BannerHero props to utils.

---

browser-tests/event-search/eventSearchPage.components.ts

quick fix for click more events -test. It's not perfect solution a it hides the problem but at least we get the tests green and less spam

quick fix for click more events - browser test

---

browser-tests/utils/generated/graphql.ts
src/domain/collection/eventList/EventList.tsx
src/domain/eventSearch/utils.tsx
src/generated/graphql.tsx

TH-1138.
NOTE: The code does not work yet. It needs LinkedEvents v2 and event type work done before it can be continued. It also needs changes from proxy https://github.com/City-of-Helsinki/events-helsinki-api-proxy/pull/64 and cms City-of-Helsinki/events-helsinki-cms#23

Added an util that resolves event type and can be used by collections EventList.

---

src/domain/courseSearch/Search.tsx
src/domain/courseSearch/__tests__/CourseSearchPageContainer.test.tsx

TH-1111. Removed a feature setting that was left from TH-1040 in order to set the division selector visible.
NOTE: This pull request is left as a draft, because it needs LinkedEvents v2 setupped.

The division selector is now visible in course search.

---

src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/event/eventInfo/OrganizationInfo.tsx
src/domain/event/eventInfo/__tests__/EventInfo.test.tsx

TH-1140 To guide the user better, the course page publisher search link text is changed to something that describes that next query will be about courses.
NOTE: This is a self made not requested improvement.

Changed course page providers link text.

---

src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/event/eventInfo/__tests__/EventInfo.test.tsx

TH-1140. A trivial provider link text change
TH-1121. "Evenemangen" -> "Evenemang"

Translation changes to navigation links

---

src/domain/event/eventCard/largeEventCard.module.scss

fix: lined the buttons of the cards of the curated events

---

.env
.github/workflows/production.yml
.github/workflows/review.yml
.github/workflows/staging.yml
CHANGELOG.md
package.json
src/domain/app/BrowserApp.tsx

Changes from self hosted Matomo into Digia Iiris Matomo.
I tested this configuration locally. Aiski verified that Matomo received data with these configs.
Contains documentation for release 0.10.0.
**[TH-1199](https://helsinkisolutionoffice.atlassian.net/browse/TH-1199):**

TH-1199 | Replace self hosted Matomo with Digia Iiris Matomo

---

src/domain/collection/__tests__/CollectionPageContainer.test.tsx
src/domain/collection/curatedEvents/__tests__/CuratedEvents.test.tsx
src/domain/collection/curatedEvents/usePaginatedEventsByIdsQuery.tsx

TH-1203. Instead of sorting the events by an end time, they should now be sorted by a start time. This is opposite for what was decided earlier in TH-1029 and TH-1183. When the events are ordered b a start time, the long lasting events always fills the first pages, but when they are ordered by the end time, the result set looks weird and it's hard to see that long lasting events starts already.

feat: sort the events in the collection by a start time

---

browser-tests/datasources/eventDataSource.ts
src/domain/collection/curatedEvents/__tests__/CuratedEvents.test.tsx
src/domain/collection/eventList/EventList.tsx
src/domain/event/queryUtils.ts
src/domain/eventSearch/SearchPage.tsx
src/domain/eventSearch/__tests__/EventSearchPageContainer.test.tsx
src/test/apollo-mocks/eventListMocks.ts

TH-1203 TH-1204. In #341 the curated events were changed to be sorted by start time. This pull request sorts the rest / every event list by start time.

feat: sort the events in every listing by a start time
